project:
  type: website
  output-dir: docs

website:
  title: "Unashamed Curiosity"
  navbar:
    right:
      - index.qmd
      - about.qmd
format:
  html:
    theme: sketchy
    css: styles.css



