project:
  type: website
  output-dir: docs

website:
  title: "Unashamed Curiosity"
  navbar:
    right:
      - index.qmd
      - now.qmd
      - work_with_me.qmd
      - collaborators.qmd
format:
  html:
    theme: sketchy
    css: styles.css


